# Generated by Django 6.1.1 on 2026-09-18 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_expositor', models.CharField(max_length=200, verbose_name='Nombre del expositor')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Marca o nombre de la empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='expositores/logos/', verbose_name='Logo de la marca o negocio')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Correo electrónico de contacto')),
                ('numero_contacto', models.CharField(help_text='Formato: +34 123 456 789', max_length=20, verbose_name='Número de contacto')),
                ('numero_stand', models.PositiveIntegerField(help_text='Número único del stand en el festival', unique=True, verbose_name='Número de stand')),
                ('enlace_red_social_1', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace a redes sociales (principal)')),
                ('enlace_red_social_2', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace adicional de redes sociales (opcional)')),
                ('menu_completo', models.TextField(help_text='Ingresa cada producto con su precio en una línea nueva.', verbose_name='Menú completo (Lista de productos y precios)')),
                ('acepta_tarjeta', models.BooleanField(default=False, verbose_name='¿Aceptan pago con tarjeta?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar este expositor en el sitio web', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Expositor',
                'verbose_name_plural': 'Expositores',
                'ordering': ['numero_stand'],
            },
        ),
    ]
