# Generated by Django 6.1.1 on 2026-09-18 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expositor',
            options={'ordering': ['numero_stand', 'nombre_empresa'], 'verbose_name': 'Expositor', 'verbose_name_plural': 'Expositores'},
        ),
        migrations.AddField(
            model_name='expositor',
            name='direccion_negocio',
            field=models.CharField(blank=True, help_text='Escribe la dirección si no tienes link de Google Maps', max_length=300, null=True, verbose_name='Dirección del negocio'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='link_google_maps',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Google Maps de la ubicación del negocio'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='redes_sociales_texto',
            field=models.CharField(blank=True, help_text='Si no tienes URLs completas, escribe los nombres de usuario aquí', max_length=300, null=True, verbose_name='Redes sociales (texto)'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_1',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Red social principal'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_2',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Red social adicional'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='menu_completo',
            field=models.TextField(help_text='Ingresa cada producto con su precio.', verbose_name='Menú completo (Lista de productos y precios)'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_contacto',
            field=models.CharField(help_text='Formato: 914 123 4567', max_length=50, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_stand',
            field=models.CharField(blank=True, help_text='Número del stand en el festival. Puede dejarse pendiente.', max_length=50, null=True, verbose_name='Número de stand'),
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='expositores/productos/', verbose_name='Foto del producto')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.expositor', verbose_name='Expositor')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de productos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
