# Generated by Django 6.1.1 on 2026-09-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expositor_options_expositor_direccion_negocio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expositor',
            options={'ordering': ['-es_destacado', 'numero_stand', 'nombre_empresa'], 'verbose_name': 'Expositor', 'verbose_name_plural': 'Expositores'},
        ),
        migrations.AddField(
            model_name='expositor',
            name='acepta_efectivo',
            field=models.BooleanField(default=True, verbose_name='¿Acepta efectivo?'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Butifarra Tradicional'), ('especialidad', 'Especialidades'), ('mixto', 'Mixto (varios productos)'), ('quesos', 'Quesos y Embutidos'), ('bebidas', 'Bebidas y Postres')], default='tradicional', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Una o dos líneas que describan al expositor', null=True, verbose_name='Descripción corta del negocio'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='es_destacado',
            field=models.BooleanField(default=False, help_text='Se mostrará primero en la lista', verbose_name='¿Expositor destacado?'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Separa por comas. Ej: crema de ajo, mango habanero, BBQ', max_length=300, null=True, verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio más bajo del menú (solo número)', max_digits=8, null=True, verbose_name='Precio desde'),
        ),
    ]
