# Generated by Django 6.1.1 on 2026-09-23 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expositor_options_expositor_acepta_efectivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('categoria', models.CharField(choices=[('butifarra_tradicional', 'Butifarra Tradicional'), ('butifarra_especialidad', 'Butifarra de Especialidad'), ('queso', 'Queso de Puerco'), ('longaniza', 'Longaniza'), ('carne', 'Carnes'), ('patitas', 'Patitas Curtidas'), ('salsa', 'Salsas y Aderezos'), ('bebida', 'Bebidas'), ('postre', 'Postres'), ('combo', 'Combos'), ('otro', 'Otros')], default='otro', max_length=30, verbose_name='Categoría')),
                ('unidad', models.CharField(choices=[('kg', 'Kilo'), ('1/2kg', 'Medio kilo'), ('1/4kg', 'Cuarto'), ('orden', 'Orden'), ('orden_fam', 'Orden familiar'), ('orden_media', 'Media orden'), ('orden_ind', 'Orden individual'), ('pieza', 'Pieza'), ('rebanada', 'Rebanada'), ('litro', 'Litro'), ('bote', 'Bote'), ('paquete', 'Paquete'), ('unidad', 'Unidad')], default='unidad', max_length=20, verbose_name='Unidad de venta')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción corta')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible en el festival')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.expositor', verbose_name='Expositor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria'], name='core_produc_categor_e2365f_idx'), models.Index(fields=['precio'], name='core_produc_precio_f300c1_idx')],
            },
        ),
    ]
