# Generated by Django 6.1.1 on 2026-09-28 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Festival de la Butifarra', max_length=200)),
                ('edicion', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=300)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='festival/logo/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-edicion'],
            },
        ),
        migrations.AlterField(
            model_name='expositor',
            name='acepta_efectivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='acepta_tarjeta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Butifarra Tradicional'), ('especialidad', 'Especialidades'), ('mixto', 'Mixto (varios productos)'), ('quesos', 'Quesos y Embutidos'), ('bebidas', 'Bebidas y Postres')], default='tradicional', max_length=20),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='direccion_negocio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='email_contacto',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_1',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_2',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='especialidades',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='link_google_maps',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='expositores/logos/'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='menu_completo',
            field=models.TextField(help_text='Ingresa cada producto con su precio. El sistema puede parsearlo automáticamente.'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_empresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_expositor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_contacto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_stand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='redes_sociales_texto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='imagen',
            field=models.ImageField(upload_to='expositores/productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('butifarra_tradicional', 'Butifarra Tradicional'), ('butifarra_especialidad', 'Butifarra de Especialidad'), ('queso', 'Queso de Puerco'), ('longaniza', 'Longaniza'), ('carne', 'Carnes'), ('patitas', 'Patitas Curtidas'), ('salsa', 'Salsas y Aderezos'), ('bebida', 'Bebidas'), ('postre', 'Postres'), ('combo', 'Combos'), ('otro', 'Otros')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilo'), ('1/2kg', 'Medio kilo'), ('1/4kg', 'Cuarto'), ('orden', 'Orden'), ('orden_fam', 'Orden familiar'), ('orden_media', 'Media orden'), ('orden_ind', 'Orden individual'), ('pieza', 'Pieza'), ('rebanada', 'Rebanada'), ('litro', 'Litro'), ('bote', 'Bote'), ('paquete', 'Paquete'), ('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
        migrations.CreateModel(
            name='EventoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.festival')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productor', models.CharField(max_length=200)),
                ('negocio', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('expositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas', to='core.expositor')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='core.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cartel_url', models.URLField(blank=True, help_text='URL del cartel del artista')),
                ('imagen_local', models.ImageField(blank=True, null=True, upload_to='festival/artistas/')),
                ('dia_presentacion', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='core.festival')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(blank=True)),
                ('imagen_local', models.ImageField(blank=True, null=True, upload_to='festival/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to='core.festival')),
            ],
            options={
                'verbose_name_plural': 'Fotos de galería',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('parrafo', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='core.festival')),
            ],
            options={
                'verbose_name_plural': 'Historia del festival',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_local', models.ImageField(blank=True, null=True, upload_to='festival/patrocinadores/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrocinadores', to='core.festival')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('imagen_url', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa', to='core.festival')),
            ],
            options={
                'ordering': ['orden', 'dia'],
            },
        ),
        migrations.CreateModel(
            name='VideoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='URL del .mp4 o embed')),
                ('poster_url', models.URLField(blank=True)),
                ('destacado', models.BooleanField(default=False, help_text='Se muestra primero, ej. Video Oficial')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_videos', to='core.festival')),
            ],
            options={
                'ordering': ['-destacado', 'orden'],
            },
        ),
    ]
