# Generated by Django 6.1.1 on 2026-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_festival_alter_expositor_acepta_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programadia',
            name='imagen_local',
            field=models.ImageField(blank=True, null=True, upload_to='festival/programa/'),
        ),
    ]
