# Generated by Django 6.1.1 on 2026-09-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_programadia_imagen_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventointerno',
            name='festival',
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['orden'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['-edicion'], 'verbose_name': 'Festival', 'verbose_name_plural': 'Festivales'},
        ),
        migrations.AlterModelOptions(
            name='fotogaleria',
            options={'ordering': ['orden'], 'verbose_name': 'Foto de galería', 'verbose_name_plural': 'Fotos de galería'},
        ),
        migrations.AlterModelOptions(
            name='historiafestival',
            options={'ordering': ['orden'], 'verbose_name': 'Bloque de historia', 'verbose_name_plural': 'Historia del festival'},
        ),
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'ordering': ['orden'], 'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AlterModelOptions(
            name='programadia',
            options={'ordering': ['orden', 'dia'], 'verbose_name': 'Día del programa', 'verbose_name_plural': 'Programa por día'},
        ),
        migrations.AlterModelOptions(
            name='videogaleria',
            options={'ordering': ['-destacado', 'orden'], 'verbose_name': 'Video de galería', 'verbose_name_plural': 'Videos de galería'},
        ),
        migrations.AlterField(
            model_name='artista',
            name='cartel_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='acepta_efectivo',
            field=models.BooleanField(default=True, verbose_name='¿Acepta efectivo?'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='acepta_tarjeta',
            field=models.BooleanField(default=False, verbose_name='¿Aceptan pago con tarjeta?'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Butifarra Tradicional'), ('especialidad', 'Especialidades'), ('mixto', 'Mixto (varios productos)'), ('quesos', 'Quesos y Embutidos'), ('bebidas', 'Bebidas y Postres')], default='tradicional', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta del negocio'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='direccion_negocio',
            field=models.CharField(blank=True, help_text='Escribe la dirección si no tienes link de Google Maps', max_length=300, null=True, verbose_name='Dirección del negocio'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='email_contacto',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_1',
            field=models.CharField(blank=True, help_text='URL completa o nombre de usuario', max_length=500, null=True, verbose_name='Red social principal'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='enlace_red_social_2',
            field=models.CharField(blank=True, help_text='URL completa o nombre de usuario', max_length=500, null=True, verbose_name='Red social adicional'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='¿Expositor destacado?'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='especialidades',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Especialidades'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='link_google_maps',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Google Maps de la ubicación del negocio'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='expositores/logos/', verbose_name='Logo de la marca o negocio'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='menu_completo',
            field=models.TextField(help_text='Ingresa cada producto con su precio.', verbose_name='Menú completo (Lista de productos y precios)'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_empresa',
            field=models.CharField(max_length=200, verbose_name='Marca o nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_expositor',
            field=models.CharField(max_length=200, verbose_name='Nombre del expositor'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_contacto',
            field=models.CharField(help_text='Formato: 914 123 4567', max_length=50, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_stand',
            field=models.CharField(blank=True, help_text='Número del stand en el festival. Puede dejarse pendiente.', max_length=50, null=True, verbose_name='Número de stand'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio desde'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='redes_sociales_texto',
            field=models.CharField(blank=True, help_text='Si no tienes URLs completas, escribe los nombres de usuario aquí', max_length=300, null=True, verbose_name='Redes sociales (texto)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='festival',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='imagen',
            field=models.ImageField(upload_to='expositores/productos/', verbose_name='Foto del producto'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('butifarra_tradicional', 'Butifarra Tradicional'), ('butifarra_especialidad', 'Butifarra de Especialidad'), ('queso', 'Queso de Puerco'), ('longaniza', 'Longaniza'), ('carne', 'Carnes'), ('patitas', 'Patitas Curtidas'), ('salsa', 'Salsas y Aderezos'), ('bebida', 'Bebidas'), ('postre', 'Postres'), ('combo', 'Combos'), ('otro', 'Otros')], default='otro', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible en el festival'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilo'), ('1/2kg', 'Medio kilo'), ('1/4kg', 'Cuarto'), ('orden', 'Orden'), ('orden_fam', 'Orden familiar'), ('orden_media', 'Media orden'), ('orden_ind', 'Orden individual'), ('pieza', 'Pieza'), ('rebanada', 'Rebanada'), ('litro', 'Litro'), ('bote', 'Bote'), ('paquete', 'Paquete'), ('unidad', 'Unidad')], default='unidad', max_length=20, verbose_name='Unidad de venta'),
        ),
        migrations.AlterField(
            model_name='programadia',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videogaleria',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videogaleria',
            name='poster_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videogaleria',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Entrevista',
        ),
        migrations.DeleteModel(
            name='EventoInterno',
        ),
    ]
