# Generated by Django 6.1.1 on 2026-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_eventointerno_festival_alter_artista_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositor',
            name='estado_solicitud',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado y publicado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado de solicitud'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío de solicitud'),
        ),
        migrations.AddField(
            model_name='expositor',
            name='nota_admin',
            field=models.TextField(blank=True, help_text='Explicación de aprobación o rechazo (visible para el expositor).', null=True, verbose_name='Nota del administrador'),
        ),
    ]
