# Generated by Django 6.1.1 on 2026-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expositor_estado_solicitud_expositor_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositor',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión por admin'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='estado_solicitud',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('observado', 'Con observaciones'), ('aprobado', 'Aprobado y publicado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20, verbose_name='Estado de solicitud'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='menu_completo',
            field=models.TextField(blank=True, help_text='Ingresa cada producto con su precio.', null=True, verbose_name='Menú completo (Lista de productos y precios)'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_empresa',
            field=models.CharField(default='Por definir', max_length=200, verbose_name='Marca o nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nombre_expositor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del expositor'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='nota_admin',
            field=models.TextField(blank=True, help_text='Explicación de aprobación, observaciones o rechazo (visible para el expositor).', null=True, verbose_name='Nota del administrador'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='numero_contacto',
            field=models.CharField(blank=True, help_text='Formato: 914 123 4567', max_length=50, null=True, verbose_name='Número de contacto'),
        ),
    ]
