# Generated by Django 6.1.1 on 2026-10-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expositor_fecha_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositor',
            name='estado_solicitud',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('observado', 'Con observaciones'), ('aprobado', 'Aprobado y publicado'), ('rechazado', 'Rechazado'), ('revision_pendiente', 'Cambios pendientes de aprobación')], default='borrador', max_length=20, verbose_name='Estado de solicitud'),
        ),
        migrations.CreateModel(
            name='CambioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(help_text='JSON con los campos del expositor y las operaciones sobre productos/fotos.', verbose_name='Datos del cambio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('expositor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_pendiente', to='core.expositor', verbose_name='Expositor')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio pendiente',
                'verbose_name_plural': 'Cambios pendientes',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('observacion', 'Observación'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('info', 'Información')], default='observacion', max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído por el expositor?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_admin', to='core.expositor', verbose_name='Expositor')),
            ],
            options={
                'verbose_name': 'Comentario del admin',
                'verbose_name_plural': 'Comentarios del admin',
                'ordering': ['-fecha'],
            },
        ),
    ]
